If running in a x86 environment (like a testing one), installing a x86 proot for running Box86 is quite silly...

diff --git a/add_i386_support b/add_i386_support
--- a/add_i386_support
+++ b/add_i386_support
@@ -29,18 +29,52 @@ echo ""
 export PROOT_DISTRO="debian-oldstable"
 export PROOT_NAME="box86"
 
+
+ARCH=$(uname -m)
+
+if [ "$ARCH" == "i386" ];
+then
+    DISTRO_ARCH="arm"
+
+    echo "Detected i386 architecture. Installing an ARM proot."
+    echo "Installing needed packages ... "
+
+    pkg install -y qemu-user-arm qemu-user-i386
+
+    if [ "$?" == "1" ];
+    then
+        abort "Failed!"
+    fi
+
+elif [ "$ARCH" == "x86_64" ];
+then
+    DISTRO_ARCH="aarch64"
+
+    echo "Detected AMD64 architecture. Installing an ARM64 proot."
+    echo "Installing needed packages ..."
+
+    pkg install -y qemu-user-arm qemu-user-i386 \
+                   qemu-user-aarch64 qemu-user-x86-64
+
+    if [ "$?" == "1" ];
+    then
+        abort "Failed!"
+    fi
+fi
+
+
 "$PROOT_TOOLS_PATH/setup" 
 
 
 if [ "$?" == "0" ];
 then
-    "$PROOT_TOOLS_PATH/scripts/pexec_admin" $PROOT_DISTRO \
+    "$PROOT_TOOLS_PATH/scripts/pexec_admin" $PROOT_NAME \
         "apt update"
 
-    "$PROOT_TOOLS_PATH/scripts/pexec_admin" $PROOT_DISTRO \
+    "$PROOT_TOOLS_PATH/scripts/pexec_admin" $PROOT_NAME \
         "apt upgrade -y"
 
-    "$PROOT_TOOLS_PATH/scripts/pexec_admin" $PROOT_DISTRO \
+    "$PROOT_TOOLS_PATH/scripts/pexec_admin" $PROOT_NAME \
         "apt install -y dialog gpg git sudo wget"
 
     if ! [ "$?" == "0" ];
