QEMU packages should not be installed if already present.

diff --git a/install_box86_proot b/install_box86_proot
--- a/install_box86_proot
+++ b/install_box86_proot
@@ -37,14 +37,19 @@ then
     export DISTRO_ARCH="arm"
 
     echo "Detected i386 architecture. Installing an ARM proot."
-    echo "Installing needed packages ... "
-    echo "===================================================="
 
-    pkg install -y qemu-user-arm qemu-user-i386
-
-    if [ "$?" == "1" ];
+    if ! [ -f "$PREFIX/bin/qemu-arm" ] || 
+       ! [ -f "$PREFIX/bin/qemu-i386" ];
     then
-        abort "Failed!"
+        echo "Installing needed packages ... "
+        echo "===================================================="
+
+        pkg install -y qemu-user-arm qemu-user-i386
+
+        if [ "$?" == "1" ];
+        then
+            abort "Failed!"
+        fi
     fi
 
 elif [ "$ARCH" == "x86_64" ];
@@ -52,15 +57,20 @@ then
     export DISTRO_ARCH="aarch64"
 
     echo "Detected AMD64 architecture. Installing an ARM64 proot."
-    echo "Installing needed packages ..."
-    echo "======================================================="
-
-    pkg install -y qemu-user-arm qemu-user-i386 \
-                   qemu-user-aarch64 qemu-user-x86-64
-
-    if [ "$?" == "1" ];
+    
+    if ! [ -f "$PREFIX/bin/qemu-aarch64" ] || 
+       ! [ -f "$PREFIX/bin/qemu-x86_64" ];
     then
-        abort "Failed!"
+        echo "Installing needed packages ..."
+        echo "======================================================="
+
+        pkg install -y qemu-user-arm qemu-user-i386 \
+                    qemu-user-aarch64 qemu-user-x86-64
+
+        if [ "$?" == "1" ];
+        then
+            abort "Failed!"
+        fi
     fi
 fi
 
