Needs more testing but i think starting the proot and stopping it should both work now. Cheking if /var/run/sshd.pid exists isn't required because it seems to always exist.

diff --git a/proot/scripts/stop_proot b/proot/scripts/stop_proot
--- a/proot/scripts/stop_proot
+++ b/proot/scripts/stop_proot
@@ -48,13 +48,19 @@ then
 fi
 
 
+echo "Checking proot access ..."
+echo "-------------------------"
+
+check_proot $PROOT
+
+if [ "$?" == "1" ];
+then
+    abort "Failed!"
+fi
+
+
 PROOT_SSHD_PID_PATH="$PREFIX/var/lib/proot-distro/installed-rootfs"
 PROOT_SSHD_PID_PATH+="/${PROOT}/var/run/sshd.pid"
-
-if ! [ -f "${PROOT_SSHD_PID_PATH}" ];
-then
-    abort "The proot '${PROOT}' is already off."
-fi
 
 
 if ! [ "$EXT_SD" == "" ];
@@ -63,7 +69,8 @@ then
 fi
 
 
-proot-distro login $PROOT $SD_BINDING --shared-tmp -- kill -9 $(cat /var/run/sshd.pid)
+proot-distro login $PROOT $SD_BINDING \
+             --shared-tmp -- kill -9 $(cat /var/run/sshd.pid)
 
 if [ "$?" == "0" ];
 then
