Now that we are not limiting the install to Android and Termux, some work needs to be done. Rewriting Wine installation to a more cleaner version.

diff --git a/wine/install-wine32 b/wine/install-wine32
--- a/wine/install-wine32
+++ b/wine/install-wine32
@@ -31,15 +31,18 @@ fi
 
 
 
-DEFAULT_WINE_VARIANT="staging"
-DEFAULT_WINE_VERSION="8.0.0"
+SETUP_DIR=$(realpath $(dirname $0))
 
-WINE_VARIANT=$1
+DEFAULT_WINE_BRANCH="staging"
+DEFAULT_WINE_VERSION="9.3"
+
+WINE_BRANCH=$1
 WINE_VERSION=$2
 
-if [ "$WINE_VARIANT" == "" ];
+
+if [ "$WINE_BRANCH" == "" ];
 then
-    WINE_VARIANT=$DEFAULT_WINE_VARIANT
+    WINE_BRANCH=$DEFAULT_WINE_BRANCH
 fi
 
 if [ "$WINE_VERSION" == "" ];
@@ -47,15 +50,11 @@ then
     WINE_VERSION=$DEFAULT_WINE_VERSION
 fi
 
-
-WINE_BUILDS_URL="https://dl.winehq.org/wine-builds"
-DEBIAN_OLDSTABLE_BUILDS_URL="$WINE_BUILDS_URL/debian/dists/bullseye"
-
-WINE_SOURCES_URL="$DEBIAN_OLDSTABLE_BUILDS_URL/winehq-bullseye.sources"
-WINE_GPG_URL="$WINE_BUILDS_URL/winehq.key"
+DOWNLOAD_DIR=/var/tmp/wine-pkgs/$WINE_VERSION
+UNINSTALLER="$HOME/wine32-uninstaller"
 
 
-if [ -f "/opt/wine-${WINE_VARIANT}/bin/wine" ];
+if [ -f "/opt/wine-${WINE_BRANCH}/bin/wine32" ];
 then
     abort "Wine (32 bits) is already installed."
 fi
@@ -63,7 +62,7 @@ fi
 
 if ! [ -f "/usr/lib/arm-linux-gnueabihf/libvkd3d.so.1" ];
 then
-    sudo "$HOME/install-wine32-deps"
+    sudo "$SETUP_DIR/install-wine32-deps"    
 
     if ! [ "$?" == "0" ];
     then
@@ -72,150 +71,66 @@ then
 fi
 
 
-echo ""
-
-
-sudo dpkg --print-foreign-architectures | grep i386 > /dev/null
+$SETUP_DIR/download-wine $WINE_BRANCH $WINE_VERSION i386
 
 if ! [ "$?" == "0" ];
 then
-    sudo dpkg --add-architecture i386
-    echo "Added i386 architecture."
+    abort "Wine download failed."
 fi
 
 
-echo -n "Checking if Wine site is available..."
-curl -s https://dl.winehq.org > /dev/null
+$DOWNLOAD_DIR/extract
 
-if [ "$?" == "0" ];
+if ! [ "$?" == "0" ];
 then
-    WINE_URL_OK=1
-    echo "OK"
-else
-    echo "ERROR"
-fi
-
-
-if ! [ "$WINE_URL_OK" == "1" ];
-then
-    echo "Failed connecting Wine site."
-    echo "Using cached package."
-    echo ""
-
-    USE_CACHED_WINE=1
-fi
-
-
-if ! [ -f "/etc/apt/keyrings/winehq-archive.key" ];
-then
-    if ! [ -d "/etc/apt/keyrings" ];
-    then
-        sudo mkdir "/etc/apt/keyrings"
-    fi
-
-
-    if ! [ "$USE_CACHED_WINE" == "1" ];
-    then
-        sudo wget -O /etc/apt/keyrings/winehq-archive.key $WINE_GPG_URL
-    else
-        sudo cp "$HOME/deb/winehq.key" /etc/apt/keyrings/
-    fi
-
-
-    if ! [ "$?" == "0" ];
-    then
-        abort "Failed adding GPG key."
-    fi
-
-    echo "Added GPG key to keyrings."
-fi
-
-
-if ! [ "$USE_CACHED_WINE" == "1" ];
-then
-    echo "Cleaning old Wine downloads..."
-    rm $HOME/wine*.deb > /dev/null
-
-
-    echo ""
-    echo "Checking for updated APT sources.list..."
-    echo "----------------------------------------"
-    sudo wget -NP /etc/apt/sources.list.d/ $WINE_SOURCES_URL
-    
-    if [ "$?" == "0" ];
-    then
-        echo "Updated sources.list in APT database."
-    fi
-
-
-    echo ""
-    echo "Updating APT database..."
-    echo "------------------------"
-
-    sudo apt update
-
-
-    echo ""
-    echo "Downloading wine-${WINE_VARIANT} (${WINE_VERSION})..."
-    echo "-----------------------------------------------------"
-
-    apt download wine-$WINE_VARIANT:i386=$WINE_VERSION~bullseye-1
-    apt download wine-$WINE_VARIANT-i386:$WINE_VERSION~bullseye-1
+    abort "The extraction failed."
 fi
 
 
 echo ""
-echo "Installing ..."
-echo "--------------"
+echo "Installing Wine ..."
+echo "-------------------"
 
 
-if ! [ "$USE_CACHED_WINE" == "1" ];
+if [ -d "/opt/wine-${WINE_BRANCH}/bin/wine" ];
 then
-    dpkg-deb -x $(ls wine-${WINE_VARIANT}_*i386.deb) \
-            "/var/tmp/wine"
+    echo "Backing up the old installation first..."
+    sudo mv /opt/wine-${WINE_BRANCH} /opt/wine-${WINE_BRANCH}-old
 
+    if ! [ "$?" == "0" ];
+    then
+        abort "Something failed."
+    fi
 
-    dpkg-deb -x $(ls wine-${WINE_VARIANT}-i386*.deb) \
-            "/var/tmp/wine"
-else
-    dpkg-deb -x $(ls $HOME/deb/wine-${WINE_VARIANT}_*i386.deb) \
-            "/var/tmp/wine"
-
-
-    dpkg-deb -x $(ls $HOME/deb/wine-${WINE_VARIANT}-i386*.deb) \
-            "/var/tmp/wine"
+    echo "Done."
 fi
 
 
-if ! [ -f "/var/tmp/wine/opt/wine-${WINE_VARIANT}/bin/wine" ];
+sudo cp -r $DOWNLOAD_DIR/opt/wine-$WINE_BRANCH /opt/
+
+sudo cp -r $DOWNLOAD_DIR/usr/share/doc/wine-${WINE_BRANCH} /usr/share/doc/
+
+sudo cp -r $DOWNLOAD_DIR/usr/share/lintian/overrides \
+           /wine-${WINE_BRANCH}-i386 /usr/share/lintian/overrides/
+
+if ! [ "$?" == "0" ];
 then
-    abort "Failed extracting Wine in /var/tmp/wine."
+    abort "Failed copying files."
 fi
 
-
-sudo cp -r /var/tmp/wine/opt/wine-${WINE_VARIANT} /opt/
-
-sudo cp -r /var/tmp/wine/usr/share/doc \
-           /wine-${WINE_VARIANT} /usr/share/doc/
-
-sudo cp -r /var/tmp/wine/usr/share/lintian/overrides \
-           /wine-${WINE_VARIANT}-i386/usr/share/lintian/overrides/
-
-
-UNINSTALLER="$HOME/wine32-uninstaller"
 
 echo "#!/bin/bash" > "$UNINSTALLER"
 echo "" >> "$UNINSTALLER"
-echo "if ! [ -f \"/opt/wine-${WINE_VARIANT}/bin/wine\" ];" >> "$UNINSTALLER"
+echo "if ! [ -f \"/opt/wine-${WINE_BRANCH}/bin/wine\" ];" >> "$UNINSTALLER"
 echo "then" >> "$UNINSTALLER"
 echo "    echo \"Didn't found Wine installed.\"" >> "$UNINSTALLER"
 echo "    exit 1" >> "$UNINSTALLER"
 echo "fi" >> "$UNINSTALLER"
 echo "" >> "$UNINSTALLER"
-echo "sudo rm -rf /opt/wine-${WINE_VARIANT}" >> "$UNINSTALLER"
-echo "sudo rm -rf /usr/share/doc/wine-${WINE_VARIANT}" >> "$UNINSTALLER"
+echo "sudo rm -rf /opt/wine-${WINE_BRANCH}" >> "$UNINSTALLER"
+echo "sudo rm -rf /usr/share/doc/wine-${WINE_BRANCH}" >> "$UNINSTALLER"
 
-echo "sudo rm -rf /usr/share/lintian/overrides/wine-${WINE_VARIANT-i386}" \
+echo "sudo rm -rf /usr/share/lintian/overrides/wine-${WINE_BRANCH}-i386" \
      >> "$UNINSTALLER"
 
 echo "" >> "$UNINSTALLER"
@@ -224,20 +139,7 @@ echo "Done." >> "$UNINSTALLER"
 echo "" >> "$UNINSTALLER"
 
 
-sudo boxify /opt/wine-${WINE_VARIANT}/bin/wine /usr/local/bin/wine
-
-
-echo "Finished. Execute ${UNINSTALLER} to remove Wine."
 echo ""
-
-
-
-
-
-
-
-
-
-
-
-
+echo "Finished."
+echo "You can find also an uninstaller: ${UNINSTALLER}"
+echo ""
