Almost done...

diff --git a/wine/install-wine32 b/wine/install-wine32
--- a/wine/install-wine32
+++ b/wine/install-wine32
@@ -15,15 +15,24 @@ function abort
 }
 
 
-
-
 if [ "$TERMUX_VERSION" == "" ];
 then
     abort "This script is for Termux only."
 fi
 
 
-if [ -f "/usr/bin/wine32" ];
+
+
+WINE_BUILDS_URL="https://dl.winehq.org/wine-builds"
+DEBIAN_OLDSTABLE_BUILDS_URL="$WINE_BUILDS_URL/debian/dists/bullseye"
+
+WINE_SOURCES_URL="$DEBIAN_OLDSTABLE_BUILDS_URL/winehq-bullseye.sources"
+WINE_GPG_URL="$WINE_BUILDS_URL/winehq.key"
+
+WINE_VARIANT="staging"
+
+
+if [ -f "/usr/bin/wine" ];
 then
     abort "Wine (32 bits) is already installed."
 fi
@@ -38,5 +47,62 @@ then
         abort "Some required wine32 dependencies failed to install."
     fi
 fi
+
+
+echo ""
+
+
+dpkg --add-architecture i386
+echo "Added i386 architecture."
+
+
+if ! [ -d "/etc/apt/keyrings" ];
+then
+    mkdir "/etc/apt/keyrings"
+fi
+
+
+sudo wget -O /etc/apt/keyrings/winehq-archive.key $WINE_GPG_URL
+
+if ! [ "$?" == "0" ];
+then
+    abort "Failed adding GPG key."
+fi
+
+echo "Added GPG key to keyrings."
+
+
+sudo wget -NP /etc/apt/sources.list.d/ $WINE_SOURCES_URL
+
+echo "Added sources.list to APT database."
+
+
+echo "Updating APT database..."
+echo "------------------------"
+
+apt update
+
+
+echo ""
+echo "Downloading wine..."
+echo "-------------------"
+
+apt download wine-$WINE_VARIANT
+apt download wine-$WINE_VARIANT-i386
+
+
+echo ""
+echo "Installing ..."
+echo "--------------"
+
+dpkg-deb -x $(ls wine-${WINE_VARIANT}_*.deb) \
+         "/opt/wine-$WINE_VARIANT"
+
+
+dpkg-deb -x $(ls wine-${WINE_VARIANT}-i386*.deb) \
+         "$HOME/.local/installs/wine-$WINE_VARIANT"
+
+
+if [ -f "$HOME/.local/installs/wine-$WINE_VARIANT/" ]
 
 
